### ISSUE TITLE
Some Primero cases not being sent to Oscar in f1-j2

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#109]
# Bug Report

## Background, context, and business value
I created 4 cases in Primero with the case_ids below to test syncing multiple Oscar cases and decisions back to Primero. When I run the [f1-j1](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j1-getPrimeroCasesV2.js) job, the run [log](https://openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06256b13-762c-735c-ae94-7534841c6934) looks correct and I can see all of the cases and services I created in the initial state of the f1-j2 [run](https://openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06256b13-d5f3-768c-9d14-38f53c8e0eea). So why is only one case (` "case_id": "702ea88a-a27a-464a-aa80-fb15872e8b09"`) being sent to Oscar at the end of the f1-j2 run? See line 2143 in the log. 

Cases I created: 
`case_id: '702ea88a-a27a-464a-aa80-fb15872e8b09'`
`case_id: 'f0a068d7-e45a-4c4d-932c-9434e0948088'` 
`case_id: '9daa8f9e-21d8-4aa8-ab05-034107839b1b'` 
`case_id: 'fc796dda-4ac2-4040-b46d-b6b99f8a3607'`

The job should be sending all 4 cases to Oscar. I can confirm that this was working properly two weeks ago. I created these cases Tuesday afternoon and have updated the f1-j1 cursor to just before they were created. 

## state.json

f1-j1
```json
{
"configuration": "Primero V2 Cambodia Demo (openfn_cp_user)",
}
```
f1-j2
```json
{
"configuration": "Oscar Staging (api only user)",
"data": "Data will be generated from f1-j1"
}
```

## adaptor
`language-http`

## expression.js
[f1-j2-casesToOscar](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js)

**Comment by daissatou2** [comment]
See slack [thread](https://openfn.slack.com/archives/G2LJCFFDW/p1649786411052039) for previous conversation here

**Comment by aleksa-krolls** [comment]
@daissatou2 please test today to inform whether further changes are needed.
