### ISSUE TITLE
Add a new field mapping to the f1-j2-casesToOscar job

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#111]
## Background, context, and business value

Add a new field mapping to the [f1-j2-casesToOscar](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js) job.

## The specific request, in as few words as possible
Add the `date_of_referral` field to the `casesToOscar` job mapping. The details for the new field have been added to the [mapping specifications.](https://docs.google.com/spreadsheets/d/1Zg9KGkHbh0ptjpj4YX9qFkojz9ydJ9aVT_UtkvE7Wu8/edit#gid=744794061&range=C30)

Note: the source data is on the referral response from Primero. Check out this sample [referral response](https://github.com/OpenFn/primero-progres/blob/master/sampleData/getPrimeroReferral.json#L18) .

## state.json
Primero (to generate state)
```json
{
"configuration": "Primero V2 Cambodia Demo API user",
}
```
Oscar:
```json
{
"configuration": "Oscar Staging (api only user)",
"data": "Data will be generated from f1-j1 job"
}
```

**Comment by aleksa-krolls** [comment]
@daissatou2 fyi, this issue was added to the wrong repo... I transferred here. 

I think I've now implemented this change. Can you please test by sending a Primero referral to Oscar to confirm? Holler if issues, thanks!
