### ISSUE TITLE
f2-j2-upsertCasesToPrimero job failing to sync Oscar decisions to Primero

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#113]
# Bug Report

## Describe the bug
We are seeing a **green check** for a [run](https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06290b98-3208-7807-ac50-10f8ba8d2fb0) with an error message for the [f2-j2-upsertCasesToPrimero](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js]) job. 
**Error message:** (`node:2256147) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uuid' of undefined`

In the run above, we were testing syncing the Oscar decision for case where `"external_id": "39051cfc-a2fe-4f97-8323-e7c52a07441a"` to Primero. According to line 358 of the log, it looks like the job successfully finds the matching referral that should be updated with the decision but does not actually [update the case](https://github.com/OpenFn/unicef-cambodia/blob/0b78b068c6b001a58d911774fad6afaa014cfafa/jobs/V2/f2-j2-upsertCasesToPrimero.js#L582). 

Note: this test scenario passed when we last tested 3 weeks ago. 

## To Reproduce
Run [f2-j1](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j1-getOscarCases.js) after clearing the state (I have updated the manual cursor). In the response received from Oscar,  use the case where `"external_id": "39051cfc-a2fe-4f97-8323-e7c52a07441a",` as initial state for `f2-j2`. 
 

## state.json
Primero:
Oscar (to generate state):

{
"configuration": "Oscar Staging (api only user)",
}

{
"configuration": "Primero V2 Cambodia Demo (openfn_cp_user)",
"data": "Run F2-J1 to generate state"
}

## expression
**Please only modify jobs in the `V2` folder!**
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js

This is a staging environment, so feel free to run repeated tests locally. 

## adaptor 
`language-primero@2.7.0`

**Comment by aleksa-krolls** [comment]
@taylordowns2000 this is priority this week. Pls check out the full run log error... at a glance, I wonder if this is actually adaptor related. Do you have time today or tomorrow to take a look? 

@daissatou2 is available for pairing, as needed, so keep her posted.

**Comment by taylordowns2000** [comment]
@daissatou2 , adding a comment here for posterity! this is ready for your and @aleksa-krolls 's review/discussion.

**Comment by aleksa-krolls** [comment]
In sum, the change implemented here was to make sure that cases had a referral service where `enrollment_date === null`, before classifying this service as a "decision". This is because all services sent from Primero to Oscar do _not_ have `enrollment_date`. Only Oscar program services (not referrals) do have `enrollment_date`. 

Related slack thread: https://openfn.slack.com/archives/C017ELVRSM8/p1653927956063479?thread_ts=1653911584.650449&cid=C017ELVRSM8
