### ISSUE TITLE
Update how f1-j2-casesToOscar.js maps "referral_status" field

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#117]
# Feature Request 

## Background, context, and business value

@aleksa-krolls we need to update this [code](https://github.com/OpenFn/unicef-cambodia/blob/c79356a66c8b9aa6790797383ef7d22eb541dfa3/jobs/V2/f1-j2-casesToOscar.js#L188) using the new `referral_id`. We are currently only syncing decisions for the most recent Primero referral. Instead, the job should sync any new decisions for any referral (regardless of the order in which it was received). 

## state.json
[f1-j1-getPrimeroCasesV2.js](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j1-getPrimeroCasesV2.js)
```json
{
  "configuration": ["SEE LAST PASS: 'Primero V2 Cambodia Demo (openfn_cp_user)'"],
}
```

[f1-j2-casesToOscar.js](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js)
```json
{
  "configuration": ["SEE LAST PASS: 'Oscar Staging (api only user)'"],
  "data": "Data generated from F1-J1 job run",
}
```

## expression.js
[f1-j2-casesToOscar.js](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js)

**Comment by daissatou2** [comment]
@aleksa-krolls creating this placeholder GH issue for us to think about when Kiry resolves the API error/we get more clarity on next steps.

**Comment by daissatou2** [comment]
see [slack](https://openfn.slack.com/archives/D01ER90662J/p1659007460929809?thread_ts=1658986498.452639&cid=D01ER90662J) for latest @aleksa-krolls.

**Comment by aleksa-krolls** [comment]
@daissatou2 fyi - I think I resolved this in the [commit](https://github.com/OpenFn/unicef-cambodia/commit/9aea5a11eb9c4edd69774da08a0d4edf8c67c1dd) for #116  - no longer only checking for the most recent Primero service. Instead, we send any decision where status is accepted or exited (aka !== 'Referred'). See below. 
https://github.com/OpenFn/unicef-cambodia/commit/9aea5a11eb9c4edd69774da08a0d4edf8c67c1dd#diff-597dbdf1623947cf04f72f9f6dd113973ab3184eda28e5af44a355869da2c4adR239-R244
