### ISSUE TITLE
Map new Oscar "referral_status" field to Primero "referral_status_edf41f2"

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#118]
# Feature Request

## Background, context, and business value

We currently map the Oscar decision from the `status` field on the case-level to the Primero`referral_status_edf41f2` field on the service-level. 

## The specific request, in as few words as possible

Instead, this job should map the `referral_status` field in the Oscar response to the the Primero`referral_status_edf41f2` field. 

See sample Oscar response for several cases in this [run log](https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/062e41b0-d315-77fe-b9cb-0e49bfb0cf8c). 

## state.json

f2-j1
```json
{
  "configuration": ["SEE LAST PASS: 'Oscar Staging (api only user)'"],
  "data": "Data generated from F1-J1 job run",
}
```

j2-j2
```json
{
  "configuration": ["SEE LAST PASS: 'Primero V2 Cambodia Demo (openfn_cp_user)'"],
}
```

## expression.js
[f2-j2-upsertCasesToPrimero](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js#L480)

**Comment by aleksa-krolls** [comment]
@daissatou2 I think the commit linked to above solves this. I've tried now mapping Oscar.service.referral_status to Primero.service.referral_status_edf41f2. Can you pls test?
