### ISSUE TITLE
Date filter not returned in correct format

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#13]
https://github.com/OpenFn/unicef-cambodia/blob/91c0b7e27addca4639b37b2380ee032514149989/jobs/f2-j1-getOscarCases.js#L25

In GET request to Oscar, `state.lastQueryDate` returns this value `1587772527000` instead of '2020-01-01' (YYYY-MM-DD). Causes error. 

```
query: {
      since_date: state.lastQueryDate || '2020-01-01',
    }

**Comment by aleksa-krolls** [comment]
@taylordowns2000 We need to return date in the format `'2020-01-01 00:00:00'`, so please add the timestamp to what we have here. 

https://github.com/OpenFn/unicef-cambodia/blob/932c0121fe8778ec463e0b182f2034eb27059902/jobs/f2-j1-getOscarCases.js#L36

FYI - For now we will keep the date filters as is pending further discussion & testing.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , see this above (last) commit. can you confirm that this filter should be submitted in UTC time?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Yes, that works
