### ISSUE TITLE
Only upsert 1 case at a time to Oscar

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#16]
https://github.com/OpenFn/unicef-cambodia/blob/932c0121fe8778ec463e0b182f2034eb27059902/jobs/f1-j2-casesToOscar.js#L29

Kiry confirmed that if we only upsert 1 case at a time to Oscar, Oscar will respond with upsert status and Id for that individual record upload (eliminating the need to access the separate `/transactions` endpoint in a third step). 

Can you please upload to only post 1 Primero case at a time to Oscar? (Rather than a bulk upsert to Oscar)

**Comment by taylordowns2000** [comment]
@aleksa-krolls , i've done so in the above commit, but their API docs still specify an array. I wonder if we shouldn't post an object, rather than an array with 1 object.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Kiry confirmed that we should post one object (not an array). See below for the new format he shared. Can you implement this morning so we can check if we get around that 422 error? 

```
{ 
  "organization": {
      "global_id": "",
      "external_id": "18de3e64-437e-4987-aeb8-f0ce8e22fad7",
      "external_id_display": "18de3e64-437e-4987-aeb8-f0ce8e22fad7",
      "mosvy_number": "12232",
      "given_name": "Mana",
      "family_name": "Mono",
      "gender": "",
      "date_of_birth": "2020-04-14",
      "location_current_village_code": "",
      "address_current_village_code": "",
      "reason_for_referral": "",
      "reason_for_exiting": "",
      "organization_id": null,
      "organization_name": "cif",
      "external_case_worker_name": "Chocho",
      "external_case_worker_id": "1",
      "external_case_worker_mobile": "098443332",
      "protection_status": "He need to move to close school.",
      "services":  [
          {
              "id": 7,
              "name": "Kinship care"
          },
          {
              "id": 9,
              "name": "Family preservation"
          }
      ]
    }
}

**Comment by aleksa-krolls** [comment]
@taylordowns2000 `TypeError: Cannot read property 'replace' of undefined` when running on prod...
https://www.openfn.org/projects/1671/runs/8682690

**Comment by aleksa-krolls** [comment]
Looks like maybe services is blank and throwing the below error. How can we ensure we always successfully post to Oscar, even if Primero doesn't provide us a full set of values? @taylordowns2000 

`TypeError: Cannot read property 'map' of undefined`
https://www.openfn.org/projects/1671/runs/8683475
