### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#18]
https://github.com/OpenFn/unicef-cambodia/blob/458e1b64875bfbf657deb841c66f0ce82ae44be6/jobs/f1-j1-getPrimeroCases.js#L23

Quoin asked that we filter by `transitions_changed_at` (no longer `transitions_created_at`). So when I implemented that change, and Primero responded with 0 cases... the run failed.  
- See failed run [here](https://www.openfn.org/projects/1671/runs/8722432). 
`TypeError: Cannot read property 'split' of undefined`
- This job needs to handle when Primero responds with 0 cases. 

**NOTE: For end-user testing, I have changed back to `transitions_created_at` for now... but this job still needs to handle a response with 0 cases. And can we ensure `f2-j1` does as well?**

Additionally, I wonder if there is something off with the dynamic date filtering by `lastFetch`, because [see this run](https://www.openfn.org/projects/1671/runs/8722550) from today that shows that `The last fetched transition date is: 30-03-2020` (but that's not true... that should reflect today's date).

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Still hitting an undefined issue in my last run. See here: https://www.openfn.org/projects/1671/runs/8791386

Also note that we are going to use the OR operator for filtering dates. [See API docs page 6](https://docs.google.com/document/d/1jpaT2_UBBnc3PxPYlLMBEzNUkyfuxRZiksywG5MKM0Q/edit#). Can you please check that the `lastUpdated` data includes a timestamp like `07-05-2020 00:001?

**Comment by taylordowns2000** [comment]
I've asked Alberto about this, but pushed the change for now.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Looking like we're still sometimes hitting this error. Please see [this failed run](https://www.openfn.org/projects/1671/runs/8993995). Can you let me know what we might have missed here?
```
Found cases, updating 'last created case' date.

/home/app/assets/node_modules/vm2/lib/contextify.js:230
			throw Decontextify.value(e);
			^
TypeError [Error]: Cannot read property 'split' of undefined
