### ISSUE TITLE
First User Story (Primero to Oscar)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#2]
**Flow 1: Generating government referrals**
On daily basis, (1) fetch new Primero cases. For each new case, (2) batch create/update clients in OSCaR.   

**> Step 1 (Every 24hrs): Fetch newly created cases from Primero**
1. OpenFn logs into Primero (based on API docs, looks like you need to start a new session)
2. OpenFn sends GET request to Primero to _list cases:_ `GET /api/cases?remote=true&scope[transitions_created_at]=date_range||17-Mar-2020.17-Mar-2020&scope[service_response_types]=list||referral_to_oscar`
3. Primero responds with list of cases (example response: [`list_cases_primero.json`](https://github.com/OpenFn/unicef/blob/master/sample_data/list_cases_primero.json))

**> Step 2 (Diagram Steps 8, 8a, 8b collapsed): Batch upsert cases OSCaR**
1. OpenFn logs into OSCaR
`curl -X POST -v -H 'Content-Type: application/json' http://start.oscarhq-staging.com/api/v1/auth/sign_in -d '{"email": "api.user@example.com", "password": "enter-pwd" }'`
2. OpenFn upserts clients in batches of 100: 
`POST /api/v1/organizations/clients/create_many/`

**_TESTING NOTE: Confirm upsert action when APIs are live_**

**Resources**
1. [UNICEF Diagram for flow #1](https://drive.google.com/open?id=1CLpRYniFDZOMGof_UqHuuE4gly8J-cO2)
2. [Mapping template](https://docs.google.com/spreadsheets/d/1g0bh5P_AxumlgJg1g1WPgyoMaB_ht5W9BiYp4xFqzVs/edit#gid=744794061)
3. [OSCaR API Docs](https://app.swaggerhub.com/apis/Ro51/OSCaRInterop/1.0.0#/client/addClient) (See LastPass for SwaggerHub password) --> "Regarding authentication to the endpoints we will be using [Devise Token Auth](https://github.com/lynndylanhurley/devise_token_auth#devise-token-auth) which will support Oauth2."

4. [Primero API Docs](https://docs.google.com/document/d/1jpaT2_UBBnc3PxPYlLMBEzNUkyfuxRZiksywG5MKM0Q/edit)

**Credentials**
1. Primero (see LastPass primero_cp)
2. OSCaR (see LastPass Oscar HQ)

**Comment by taylordowns2000** [comment]
Save the issues we've run into around Primero and OSCAR, this flow is done. The first job uses the primero LP, and the second uses HTTP. We'll need to keep an eye for how OSCAR does authentication, but our standard OAuth module on OpenFn should work.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Confirmed that POST requests to OSCaR API endpoints should support upserts
