### ISSUE TITLE
Primero upsert operation not reading `case_id`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#27]
https://github.com/OpenFn/unicef-cambodia/blob/e1be71675faecef8842ef42ccc295bf6ac10b596/jobs/f2-j2-upsertCasesToPrimero.js#L363

We need to search Primero for an existing case using `oscar_number` OR `case_id` external Ids.

[ In this run](https://www.openfn.org/projects/1671/runs/9165535) it looks like `case_id` is returning `undefined` in the upsert operation, even though I can see `case_id` is included in the payload. Maybe because `case_id` is currently nested under the `"child:{}"` object... should we move it to L313 under `oscar_number: c.global_id,`? 
```
Upserting: {
  "method": "GET",
  "url": "https://cpims-kh-alpha.primero.org/api/cases",
  "jar": true,
  "qs": {
    "remote": true,
    "scope": {
      "or": {
        "oscar_number": "or_op||01EAZMTZXSMMF3CQDAMQRBKTZQ",
        "case_id": "or_op||undefined"
      }
    }
  }
}
Case found. Performing update.
Data provided to Primero `upsertCase`:  {
  "remote": true,
  "oscar_number": "01EAX92DZB4BF0V4BEVQGB7QJH",
  "child": {
    "case_id": "5653a620-15c4-47e5-9388-77166d833d04",

**Comment by taylordowns2000** [comment]
Looks to me like this just hasn't been mapped. Were we waiting on them to decide on an external ID? Currently, case_id for primero is set by the `external_id` field in each Oscar case `c`. There's no data in there. Which field should we use? `global_id`? Apologies if I missed this before.
