### ISSUE TITLE
Service mappings for uuids when upserting in Primero

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#30]
https://github.com/OpenFn/unicef-cambodia/blob/c42c482823688241e0c2a867dcbae0108eead298/jobs/f2-j2-upsertCasesToPrimero.js#L276-L277

Oscar sends us services as below, which contains service `uuid` and `subtype` (BUT it doesn't look like these `uuid` and `subtype` keys are included in the JSON response from Oscar)..
- [Use this run](https://www.openfn.org/projects/1671/runs/9161990) as example state. 
```
"services": [
    [
      "1804d3de-d1d8-4647-8968-68d4985e2a1e",
      "Kinship care"
    ]
```

**Issue when uploading Oscar case data to Primero...**
When OpenFn uploads the service data to Primero, **the `uuid` is missing** (I think because `"uuid":` key is not included in Oscar response above)...
- [Use this run](https://www.openfn.org/projects/1671/runs/9161992) as example state. 
```
"services_section": [
    {
      "service_subtype": [
        "Other",
        "Other",
        "Other",
        "Other",
        "Other",
        "Other"
      ],
      "service_type": "Other",
      "service_type_text": "Other"
    }
  ],
```
Can you please  validate my thinking as to why `uuid` is not mapping? I'll have to go back to the Oscar team if yes, because according to their API docs, we expect these keys to be included in the response. 

Current Response: 
```
"services": [
    [
      "uuid-value-1",
      "service-subtype-value-1"
    ], 
```
Expected Response: 
```
"services": [
      {
        "id": 0,
        "uuid": "9672127b-769c-4a04-b8fe-41b969709d65",
        "name": "string"
      }
    ],

**Comment by taylordowns2000** [comment]
Confirmed, they send data in multiple formats. This is a _very_ bad smell—my guess is that they're using some sort of no-sql data store and dumping whatever records they find directly to us via the "API". Let's hope there's something else going on and we're at fault, but ask them to confirm whether or not they've got half the records in their DB using one format, and half using the other... totally possible if they're on something like MongoDB.

**Comment by aleksa-krolls** [comment]
Resolved by fix on Oscar side last week.
