### ISSUE TITLE
Calculate age based on DOB

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#43]
We'll receive a `date_of_birth` from Oscar like... `"date_of_birth": "2012/05/10", `. Please add a calculation to return `age` based on DOB. Currently I have `0` as an age placeholder. 

https://github.com/OpenFn/unicef-cambodia/blob/4ab6648ab61829ed454057b4d1c91eb78086afc5/jobs/f2-j2-upsertCasesToPrimero.js#L348
Here we return a `null` value if the case was already registered in Primero to prevent data overwrites.

**Comment by taylordowns2000** [comment]
remember to handle for _both_ `''` and `undefined`
