### ISSUE TITLE
Modify gender data transformation

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#44]
https://github.com/OpenFn/unicef-cambodia/blob/4ab6648ab61829ed454057b4d1c91eb78086afc5/jobs/f2-j2-upsertCasesToPrimero.js#L346
Here we need to...
(1) Return a null value if the case was already registered in Primero to prevent data overwrites.
`c.external_id && c.external_id !== '' ? null : c.gender`
(2) AND return `'other'` value if `c.gender` does _not_ equal `'male'`, `'female'`, `null`, or `''`.  (This has been partly been implemented on L346.)

**Comment by taylordowns2000** [comment]
- _never_ update the gender if there is an `externalId`
- make sure this works with empty string as well as with undefined
- after the externalID check, then `if (c.gender not in ['male', 'female', '', undefined, null]) { 'other' } else { return the thing }`
