### ISSUE TITLE
Add `enrollment_date` mapping to Services array

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#49]
We need to add a new `service_implemented_day_time` mapping when we upload Primero service data....
https://github.com/OpenFn/unicef-cambodia/blob/2ad697d0e35eb8fd4bbc38832b6085d17cd4b2c3/jobs/f2-j2-upsertCasesToPrimero.js#L280-L306

Oscar will respond to **f2-j1** with [this state](https://gist.github.com/aleksa-krolls/3ac04eb41455c3373944bd202dc69586) where `enrollment_date` will be added to Services. 
```
{
  "enrollment_date": "2020-07-12",
  "uuid": "fad739ec-b0ab-47f3-8f1c-1a17c09a6287",
  "name": "Social Work / Case Work",
},
```
Update Primero mappings so that the `enrollment_date` is converted to the Primero format `dd-mmm-yyyy hh:mm`:  
```
.map(s => { 
     return { 
       unique_id: s.uuid, 
       service_implemented_day_time: s.enrollment_date,  //convert data format & check that not undefined or empty string
```
*Keep in mind that Oscar is still implementing `enrollment_date`, so I'm not confident it will be included in historical data... so please handle for this key not existing or returning undefined or empty string.

**Comment by taylordowns2000** [comment]
hey @aleksa-krolls , i see a lot of datetimes in primero that use this format:
```js
registration_date: oscarValue(c.external_id)
          ? null
          : now.toISOString().split('T')[0].replace(/-/g, '/'),
```
that's an ISO string `'2020-07-22T22:59:41.420Z'` with the `T` pulled out and then the `-`'s turned to `/`s. Do we want that, or that `dd-mmm-yyyy hh:mm` format?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Alberto says `dd-mmm-yyyy hh:mm` so let's go with that.

**Comment by taylordowns2000** [comment]
OK, happy to do this, but are they asking us to forge the `hh:mm` part if it's not present in the source data? If so, what time do they want us to pretend the case was enrolled? I'll assume `00:00` for now. (This raises so many red flags, but nothing we haven't warned them repeatedly about thus far.)

**Comment by taylordowns2000** [comment]
![image](https://user-images.githubusercontent.com/8732845/88238986-5ee10580-cc40-11ea-9057-0c301ae4d54b.png)

**Comment by taylordowns2000** [comment]
oh wow, sorry, just realizing that they want month spelled out as a three letter abbreviation. reopening this to work on it.

**Comment by taylordowns2000** [comment]
I've changed this to use lower-case-only three letter abbreviations for the month, per Alberto's request:
![image](https://user-images.githubusercontent.com/8732845/88239218-0100ed80-cc41-11ea-8faa-8e0e8234c2c9.png)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 OpenFn jobs are sometimes returning `"service_implemented_day_time": "NaN-undefined-NaN 00:00",`. 
[See run failure here](https://www.openfn.org/projects/1671/runs/9439495).

**Comment by aleksa-krolls** [comment]
@taylordowns2000 I think is was resolved, no related errors recently popping up. Please confirm no outstanding questions? See my last comment above.

**Comment by taylordowns2000** [comment]
This is now handled in `convertDate` lines 278-301... if Oscar does not send a date (by `oscarValue` standards) we return null rather than trying to parse the date string and returning those `NaN`s

https://github.com/OpenFn/unicef-cambodia/blob/0902e3642377a890033a42c16e39afc11dd6eafb/jobs/f2-j2-upsertCasesToPrimero.js#L278-L301
