### ISSUE TITLE
Date filter returning undefined in Primero GET request

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#5]
https://github.com/OpenFn/unicef-cambodia/blob/275ef75176c1241503a223da3ac2d353b3d1f220/jobs/f1-j1-getPrimeroCases.js#L6

`${state.lastFetch`} returning undefined when fetching cases from Primero in a GET request. 

See the failed run [here](https://www.openfn.org/projects/1671/runs/8474814): 
`"query": "remote=true&scope%5Btransitions_created_at%5D=date_range%7C%7Cundefined.30-Mar-2020&scope%5Bservice_response_types%5D=list%7C%7Creferral_to_oscar",`

This job has run a few times already in OpenFn prod (it's not the first time) so I would expect this date to be populated. I know I was hardcoding this into state when offline testing, so where should this `lastFetch` date come from? Is this logic built into the LP? Or should this job's trigger be configured in a particular way to look to previous runs?

**Comment by taylordowns2000** [comment]
Hey @aleksa-krolls , do you know what field we should use for this? We were expecting to see an `updated_at` timestampt somewhere in the case object returned, but we've only got created at. Let's discuss when you get a chance.
