### ISSUE TITLE
Upsert cases in Oscar job times out

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#56]
**Issue**
We receive 100+ cases when we fetch from the Primero API in `f1-j1` ([see run here](https://www.openfn.org/projects/1671/runs/9988056)). 

This causes `f1-j2-casesToOscar.js` to time out - see run [example 9988060](https://www.openfn.org/projects/1671/runs/9988060). 

**To replicate**
Run `f1-j1-getPrimeroCases.js`. One question that might be affecting the data volume size here - are we filtering cases by dates properly when we fetch from Primero? Looking at the `f1-j1` logs the date looks like it's in a weird format...
```
Found new cases, updating 'last created case' date.
Found cases w/ updates, updating 'last updated case' date.
The last transition update is now: 25-09-2020 11:26
The last transition creation is now: 25 11:26:28 +0000-09-2020
Finished.
```

**Comment by taylordowns2000** [comment]
This no longer times out, as it's granted `long_run` permission. I don't think the `f1-j1` cursor is working anymore, however, and there appears to be a load issue throwing a `422` in oscar.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Confirmed that the `f1-j1` cursor is no longer working because it works fine when I hardcode a date value. This works okay for testing for now, but when you get the chance over the next day - can you please check this out? 

Pretty sure the issue is with the `transitions_created_at` date format - see below snippet from the latest run. 
`The last transition creation is now: 25 11:26:28 +0000-09-2020`

**Comment by taylordowns2000** [comment]
Looks like we've got a new format in the response from Primero.  Checking it out now.
![image](https://user-images.githubusercontent.com/8732845/94574126-af8d6400-026a-11eb-8507-2f21930e0db2.png)

**Comment by taylordowns2000** [comment]
They seem to send back some really funky dates... not sure we can trust this for a cursor.
![image](https://user-images.githubusercontent.com/8732845/94578516-bb2f5980-026f-11eb-8fa4-a5b10cde4693.png)

**Comment by taylordowns2000** [comment]
cursor fixed!
