### ISSUE TITLE
f2-j2: Merge services with Primero before uploading Oscar cases

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#59]
## Background
In previous testing, Oscar would always send us cases with services. 
With Rotati's latest changes, we are now sometimes receiving Oscar cases with _no_ services linked. Now that Oscar sometimes sends us cases _without_ services, we found in testing that when we send an Oscar case with _no_ services --> Primero, then this overwrites (and thereby deletes) any existing services in Primero. 

## Change Request
Merge `services` and `transitions` using `services.uuid` before upserting a case to Primero. This will ensure that (1) existing Primero services will remain in tact as is, and (2) append new Oscar services to the Primero case. 

Primero remains the system of record. If a Primero service exists with the matching `uuid` of an incoming Oscar service, then the Primero service should remain unchanged --> drop this Oscar service from the update sent to Primero.

**Comment by taylordowns2000** [comment]
This is closed by https://github.com/OpenFn/language-primero/releases/tag/v1.1.0
