### ISSUE TITLE
Clone platform project configuration of project `pdngk6` to a new project space

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/unicef-cambodia#76]
# Feature Request

## The specific request, in as few words as possible

We'd like to set up a staging OpenFn project space for this project to be used for training. Please clone the OpenFn project configuration of `pdngk6` to a new project space.

**Comment by ritazagoni** [comment]
@taylordowns2000 Is this enough detail for the issue?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 We can probably do this by hand in 15 minutes, so let us know if going to be more than than and we'll do it manually @ritazagoni

**Comment by taylordowns2000** [comment]
Ah yes, definitely more than 15 minutes to write the required DB queries
for project, triggers, creds, jobs, project_users, auth_methods, and
job_sources (github). Please go ahead and do it manually. Down the line,
this should certainly be a feature though, re: our discussion of "sandbox"
projects linked to main projects.
