### ISSUE TITLE
F2-J2: ReferenceError [Error]: s is not defined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/unicef-cambodia#81]
## Bug
When syncing data from Oscar (F2-J1), the case upsert in Primero fails with `ReferenceError [Error]: s is not defined`
https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06193b18-01ec-7e78-ac4e-eb1a690a54f6

Feel free to re-run `F2-J1`  on platform to retry: 
https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06193b17-9b10-706e-840e-888bc77eaf4f

## expression
**Edit jobs in the `V2` directory only.**
https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/jobs/jv79xn
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js

## state 
See parent run: https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06193b17-9b10-706e-840e-888bc77eaf4f
See LP: 
`Primero V2 Cambodia Demo API user`
`Oscar Staging (api only user)`

**Comment by lakhassane** [comment]
@aleksa-krolls issue fixed. There were a misuse between `service` and `oscarService` in the code.

However hitting a `500` here: https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06193c2c-6801-7bff-879a-4654b84a7639
