### ISSUE TITLE
Primero get cases job cursor is not only fetching cases since the last sync

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#83]
# Bug Report

## Background, context, and business value

Please make sure the Primero get cases job is **only fetching cases that have been created or updated since the last sync.** It looks like the job is currently fetching cases outside of this requirement. 

See this run from yesterday: https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/06195800-7c47-7156-908c-9d2e1ba2cfc3

case_id 4D3B877 was not updated yesterday but it's being sent to OSCaR again. Let me know when you are testing and I can create test data.

## expression.js
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j1-getPrimeroCases.js

**Comment by aleksa-krolls** [comment]
@lakhassane @daissatou2 how's this going? Any help needed today?

**Comment by lakhassane** [comment]
@daissatou2 this is ready for testing!

**Comment by daissatou2** [comment]
Hey @lakhassane added an error I am seeing to slack: https://openfn.slack.com/archives/G2LJCFFDW/p1637585041011100
Here's the run: https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/0619b9a1-e216-70e8-ad7e-9d4c54c21ad2

**Comment by lakhassane** [comment]
@daissatou2 there was a typo in `data`. Corrected: https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/0619bc41-4ef5-7fa5-8c1d-f9ef0c7c2ba1
