### ISSUE TITLE
Add new field to F2-J2 OSCaR to Primero job 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#89]
# Feature Request

## Background, context, and business value

Please add this field mapping to the job: `services[][enrollment_date]`

It is highlighted in green in the mapping [specs](https://docs.google.com/spreadsheets/d/1Zg9KGkHbh0ptjpj4YX9qFkojz9ydJ9aVT_UtkvE7Wu8/edit#gid=112592766&range=B33). It should be added here: https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js#L266-L280

## state.json

```json
{
  "configuration": 
Primero V2 Cambodia Demo API user
Oscar Staging (api only user)
  "data": Run F2-J1 to generate state
}
```

## expression.js
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js

**Comment by lakhassane** [comment]
@daissatou2 I added the new field to the mapping.
