### ISSUE TITLE
Primero -> Oscar flow: Update 'f2-j2-upsertCasesToPrimero' job to include syncing of referral decision from flow 1

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#90]
# Feature Request

## Background, context, and business value

The Primero and Oscar teams have agreed to include a decision flow in the solution. So we will now be syncing referral decisions back and forth between the two systems. This is similar to the decision flow we implemented for the [Primero - Progres](https://github.com/OpenFn/primero-progres) project where we (1) get the matching referral, and (2) update the referral with the decision status.

See the data flow diagram [here](https://drive.google.com/file/d/14_Nk0xML9k_0mmtI__fNGASm-brXfn-7/view?usp=sharing).

## The specific request, in as few words as possible

Make updates in the [f2-j2-upsertCasesToPrimero](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/f2-j2-upsertCasesToPrimero.js) job to sync the decisions recieved from the parent [job](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j1-getOscarCases.js).

**When Oscar sends decisions (not new referrals) to Primero, “is_referred = false”.** **For each case where "is_referred = false", follow the steps below to sync the Oscar decision to the correct case & referral in Primero.**

When we receive a decision from Oscar, it will look like [this](https://gist.github.com/daissatou2/a19b033aeac2b282aa48b5f24f4c7c61). **We will add this decision to 1) the referral AND 2) the case level in Primero** (note: this is different from the Primero-Progres implementation).

**1) Referral update:**
1. Parse the decision JSON from Oscar to find the `external_id` & `services[].uuid`
2. Get referrals for that case: `GET /cases/:id/referrals`. See sample [JSON response](https://github.com/OpenFn/primero-progres/blob/master/sampleData/getPrimeroReferral.json).
3. If no referrals are found, log an error
4. If they are found, loop through these referrals until we find the referral where `service_record_id` = `services[].uuid` from the Oscar decision
5. Once we find the matching referral record to update, pass the `id` onto the next operation...
`updateReferral(...)` to PATCH an update to the Primero `status` field with what is in the `referral_status` field from the Oscar response.
`PATCH /cases/:record_id/referrals/:id`
[See sample JSON payload](https://github.com/OpenFn/primero-progres/blob/master/sampleData/patchPrimeroReferral.json) for request body

Mappings notes for referral level update: 
if we get value "Accepted" from Oscar `referral_status` field, send value "accepted" to Primero `status` field
if we get value "Exited" from Oscar `referral_status` field, send value "rejected" to Primero `status` field

**2) Add mapping to cases-level update on the services subform:**

1. add a services_section[] mapping for Primero`referral_status_5fe9c1a` [here](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/f2-j2-upsertCasesToPrimero.js#L282-L291). The source field is the `referral_status` field from the Oscar response. See mappings below.

Mappings notes for service level update: 
if we get "Accepted" from Oscar, send "accepted_270501" to Primero
if we get "Exited" from Oscar, send "rejected_412652" to Primero

## state.json

Primero:
```json
{
  "configuration": "Primero V2 Cambodia Demo API user",
  "data": "Run F2-J1 to generate state"
}
```
Oscar (to generate state):
```json
{
  "configuration": "Oscar Staging (api only user)",
  "data": "Data will be generated from this job"
}
```

## adaptor 
Primero adaptor
[Primero API Docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api)

## expression
**All changes should be made in the V2 folder**
[f2-j2-upsertCasesToPrimero](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/f2-j2-upsertCasesToPrimero.js)

**Comment by aleksa-krolls** [comment]
@daissatou2 let's talk through this one in our call tomorrow. 
1. `Referral update` - overall looking good, but let's discuss about how we can be more specific on the mappings. 
2. `Case level update` - the existing job uses `upsertCase(...)`. Can we not just add a mapping to existing [data object](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/f2-j2-upsertCasesToPrimero.js#L503) that is being uploaded? 
3. Do we have data flow diagrams we can link to? This is always helpful for Mamadou.

**Comment by lakhassane** [comment]
@daissatou2 I added the new mapping as discussed: https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js#L294

**Comment by daissatou2** [comment]
@lakhassane I am testing syncing only the `oscar_number` from Oscar to Primero for case with `case_id` = "55647191-e544-4fda-87d8-bd118b21ed32" (so no decision has been made on this case which originated in Primero yet). But this job is failing after completing the upsert: https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/0620bbcf-1c14-7492-8edf-c60f7f6c399e

Note: I am seeing the new `oscar_number` in Primero after this sync. But why is the job failing?
