### ISSUE TITLE
Oscar -> Primero flow: Update 'f1-j2-casesToOscar' job to include syncing of referral decision from flow 1 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#91]
# Feature Request

## Background, context, and business value

The Primero and Oscar teams have agreed to include a decision flow in the solution. So we will now be syncing referral decisions back and forth between the two systems.

## The specific request, in as few words as possible
Make updates in the [f1-j2-casesToOscar](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js) [job](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j1-getOscarCases.js) to sync the decisions received from the parent [job](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j1-getPrimeroCasesV2.js).

For all cases in the [nonreferrals](https://github.com/OpenFn/unicef-cambodia/blob/29f63caea3eaff568ce897b7ea543a339d7c7f32/jobs/V2/f1-j2-casesToOscar.js#L304) array,
1. use the status in the `services_section[*].referral_status_5fe9c1a` field  in the Primero response to update the `referral_status` field in Oscar:
- if we get `accepted_270501 ` from Primero, send `Accepted` to Oscar
- if we get `rejected_412652` from Primero, send `Exited` to Oscar 

2. send "is_referred: false"

See the data flow diagram [here](https://drive.google.com/file/d/1hpfwhJQ38PznIAxByiIbTb3TQi-G3gWW/view?usp=sharing).

## state.json
Primero (to generate state):
```js
{
  "configuration": "Primero V2 Cambodia Demo API user",
  "data": "Data will be generated from this job"
}
```

Oscar:
```js
{
  "configuration": "Oscar Staging (api only user)",
  "data": "Run F1-J1 to generate state"
}
```

## adaptor
language-http

## expression.js
[f1-j2-casesToOscar](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js)

**Comment by aleksa-krolls** [comment]
@daissatou2 Overall looking good... but quick feedback: 

Re: your point 1...
1. let's change `referral_status` --> `services_section[*].referral_status` to be specific that we expect this field to be in the services subform. 
2. It's not clear what the Oscar field name is that will hold the `Accepted`/`Exited` decision. Is there a field called `Status` or something like that? 

Then, once we get updates from UNICEF and OSCaR, let's try to extract & then link to sample JSON responses to help Mamadou out.

**Comment by lakhassane** [comment]
@daissatou2 as discussed, the new fields are adding in the mapping for `nonreferrals` array.
